[project]
name = "notion"
version = "0.1.0"
description = "Tools for interacting with Notion pages."
readme = "README.md"
dependencies = [
    "mistletoe>=1.4.0",
    "requests>=2.32.3",
]

[tool.setuptools]
py-modules = ["md2notion", "notion"]
